"""suppression_rules + ct_observations content-probe prep columns

Revision ID: 0655ff23e5b5
Revises: d125148a9211
Create Date: 2026-07-05 11:56:17.100646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0655ff23e5b5'
down_revision: Union[str, None] = 'd125148a9211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppression_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('match_value', sa.String(length=320), nullable=False),
    sa.Column('scope', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_rules_rule_type'), 'suppression_rules', ['rule_type'], unique=False)
    op.add_column('ct_observations', sa.Column('http_status', sa.Integer(), nullable=True))
    op.add_column('ct_observations', sa.Column('content_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('ct_observations', sa.Column('mx_present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ct_observations', 'mx_present')
    op.drop_column('ct_observations', 'content_fingerprint')
    op.drop_column('ct_observations', 'http_status')
    op.drop_index(op.f('ix_suppression_rules_rule_type'), table_name='suppression_rules')
    op.drop_table('suppression_rules')
    # ### end Alembic commands ###
