"""evidence_events + campaign_clusters stage lock columns

Revision ID: 482998843c0a
Revises: bc05402bfd64
Create Date: 2026-07-03 19:58:14.708813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '482998843c0a'
down_revision: Union[str, None] = 'bc05402bfd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['campaign_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_events_cluster_id'), 'evidence_events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_evidence_events_event_type'), 'evidence_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_evidence_events_observed_at'), 'evidence_events', ['observed_at'], unique=False)
    op.add_column('campaign_clusters', sa.Column('stage_locked_by', sa.String(length=64), nullable=True))
    op.add_column('campaign_clusters', sa.Column('stage_locked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_clusters', 'stage_locked_at')
    op.drop_column('campaign_clusters', 'stage_locked_by')
    op.drop_index(op.f('ix_evidence_events_observed_at'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_event_type'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_cluster_id'), table_name='evidence_events')
    op.drop_table('evidence_events')
    # ### end Alembic commands ###
