"""ct_observations + watchlist_brands

Revision ID: 72c28a2f9b5e
Revises: 
Create Date: 2026-07-02 22:52:07.649675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c28a2f9b5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ct_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_host', sa.String(length=512), nullable=False),
    sa.Column('registered_domain', sa.String(length=320), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('triage_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label_final', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.String(length=64), nullable=True),
    sa.Column('model_used', sa.String(length=32), nullable=True),
    sa.Column('ti_misp_hit', sa.Integer(), nullable=True),
    sa.Column('enrichment_level', sa.String(length=16), nullable=True),
    sa.Column('registrar', sa.String(length=256), nullable=True),
    sa.Column('whois_status', sa.String(length=256), nullable=True),
    sa.Column('whois_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whois_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_asn', sa.String(length=32), nullable=True),
    sa.Column('sample_isp', sa.String(length=256), nullable=True),
    sa.Column('sample_country', sa.String(length=8), nullable=True),
    sa.Column('num_unique_ips', sa.Integer(), nullable=True),
    sa.Column('num_countries', sa.Integer(), nullable=True),
    sa.Column('num_asns', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_host', 'event_ts', name='uq_obs_host_eventts')
    )
    op.create_index(op.f('ix_ct_observations_event_ts'), 'ct_observations', ['event_ts'], unique=False)
    op.create_index(op.f('ix_ct_observations_raw_host'), 'ct_observations', ['raw_host'], unique=False)
    op.create_index(op.f('ix_ct_observations_registered_domain'), 'ct_observations', ['registered_domain'], unique=False)
    op.create_index(op.f('ix_ct_observations_risk_score'), 'ct_observations', ['risk_score'], unique=False)
    op.create_table('watchlist_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=128), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('customer_scope', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_brands_brand_name'), 'watchlist_brands', ['brand_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_brands_brand_name'), table_name='watchlist_brands')
    op.drop_table('watchlist_brands')
    op.drop_index(op.f('ix_ct_observations_risk_score'), table_name='ct_observations')
    op.drop_index(op.f('ix_ct_observations_registered_domain'), table_name='ct_observations')
    op.drop_index(op.f('ix_ct_observations_raw_host'), table_name='ct_observations')
    op.drop_index(op.f('ix_ct_observations_event_ts'), table_name='ct_observations')
    op.drop_table('ct_observations')
    # ### end Alembic commands ###
