"""watchlist_brands self_domains

Revision ID: a6f283fd1568
Revises: 7c3b00ffda82
Create Date: 2026-07-08 17:11:01.558112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f283fd1568'
down_revision: Union[str, None] = '7c3b00ffda82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_brands', sa.Column('self_domains', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_brands', 'self_domains')
    # ### end Alembic commands ###
