"""campaign_clusters + cluster_members

Revision ID: bc05402bfd64
Revises: 72c28a2f9b5e
Create Date: 2026-07-03 09:43:51.368703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc05402bfd64'
down_revision: Union[str, None] = '72c28a2f9b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('target_brand', sa.String(length=128), nullable=True),
    sa.Column('target_workflow', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('summary_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_clusters_cluster_key'), 'campaign_clusters', ['cluster_key'], unique=True)
    op.create_index(op.f('ix_campaign_clusters_confidence_score'), 'campaign_clusters', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_campaign_clusters_target_brand'), 'campaign_clusters', ['target_brand'], unique=False)
    op.create_table('cluster_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('membership_reason', sa.String(length=256), nullable=True),
    sa.Column('membership_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['campaign_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['ct_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'observation_id', name='uq_member_cluster_obs')
    )
    op.create_index(op.f('ix_cluster_members_cluster_id'), 'cluster_members', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_members_observation_id'), 'cluster_members', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_members_observation_id'), table_name='cluster_members')
    op.drop_index(op.f('ix_cluster_members_cluster_id'), table_name='cluster_members')
    op.drop_table('cluster_members')
    op.drop_index(op.f('ix_campaign_clusters_target_brand'), table_name='campaign_clusters')
    op.drop_index(op.f('ix_campaign_clusters_confidence_score'), table_name='campaign_clusters')
    op.drop_index(op.f('ix_campaign_clusters_cluster_key'), table_name='campaign_clusters')
    op.drop_table('campaign_clusters')
    # ### end Alembic commands ###
