"""campaign_clusters queue/assignment columns + analyst_dispositions

Revision ID: d125148a9211
Revises: 482998843c0a
Create Date: 2026-07-03 20:25:26.927991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd125148a9211'
down_revision: Union[str, None] = '482998843c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_guess', sa.String(length=128), nullable=True),
    sa.Column('action_taken', sa.String(length=128), nullable=True),
    sa.Column('analyst', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['campaign_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_dispositions_cluster_id'), 'analyst_dispositions', ['cluster_id'], unique=False)
    op.add_column('campaign_clusters', sa.Column('queue_status', sa.String(length=16), server_default='new', nullable=False))
    op.add_column('campaign_clusters', sa.Column('assignee', sa.String(length=64), nullable=True))
    op.add_column('campaign_clusters', sa.Column('sla_bucket', sa.String(length=16), nullable=True))
    op.add_column('campaign_clusters', sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_clusters', sa.Column('last_ranked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_clusters', 'last_ranked_at')
    op.drop_column('campaign_clusters', 'promoted_at')
    op.drop_column('campaign_clusters', 'sla_bucket')
    op.drop_column('campaign_clusters', 'assignee')
    op.drop_column('campaign_clusters', 'queue_status')
    op.drop_index(op.f('ix_analyst_dispositions_cluster_id'), table_name='analyst_dispositions')
    op.drop_table('analyst_dispositions')
    # ### end Alembic commands ###
